export const states = [
    {
        slug: "maine",
        name: "Maine",
        abbreviation: "ME",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Maine 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Maine. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for ME residents.",
        dataFile: "/data/forecast-maine.json",
        mapFile: "/images/maps/maine.svg",
        heroImage: "/images/hero/banner-me.png",
    },
    {
        slug: "new-hampshire",
        name: "New Hampshire",
        abbreviation: "NH",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast New Hampshire 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in New Hampshire. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for NH residents.",
        dataFile: "/data/forecast-new-hampshire.json",
        mapFile: "/images/maps/new-hampshire.svg",
        heroImage: "/images/hero/banner-nh.png",
    },
    {
        slug: "vermont",
        name: "Vermont",
        abbreviation: "VT",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Vermont 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Vermont. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for VT residents.",
        dataFile: "/data/forecast-vermont.json",
        mapFile: "/images/maps/vermont.svg",
        heroImage: "/images/hero/banner-vt.png",
    },
    {
        slug: "massachusetts",
        name: "Massachusetts",
        abbreviation: "MA",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Massachusetts 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Massachusetts. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for MA residents.",
        dataFile: "/data/forecast-massachusetts.json",
        mapFile: "/images/maps/massachusetts.svg",
        heroImage: "/images/hero/banner-ma.png",
    },
    {
        slug: "connecticut",
        name: "Connecticut",
        abbreviation: "CT",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Connecticut 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Connecticut. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for CT residents.",
        dataFile: "/data/forecast-connecticut.json",
        mapFile: "/images/maps/connecticut.svg",
        heroImage: "/images/hero/banner-ct.png",
    },
    {
        slug: "rhode-island",
        name: "Rhode Island",
        abbreviation: "RI",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Rhode Island 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Rhode Island. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for RI residents.",
        dataFile: "/data/forecast-rhode-island.json",
        mapFile: "/images/maps/rhode-island.svg",
        heroImage: "/images/hero/banner-ri.png",
    },
];
