export const states = [
    {
        slug: "maine",
        name: "Maine",
        abbreviation: "ME",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Maine 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Maine. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for ME residents.",
        dataFile: "/data/forecast-maine.json",
        mapFile: "/images/maps/maine.svg",
        heroImage: "/images/hero/banner-me.png",
    },
    {
        slug: "new-hampshire",
        name: "New Hampshire",
        abbreviation: "NH",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast New Hampshire 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in New Hampshire. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for NH residents.",
        dataFile: "/data/forecast-new-hampshire.json",
        mapFile: "/images/maps/new-hampshire.svg",
        heroImage: "/images/hero/banner-nh.png",
    },
    {
        slug: "vermont",
        name: "Vermont",
        abbreviation: "VT",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Vermont 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Vermont. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for VT residents.",
        dataFile: "/data/forecast-vermont.json",
        mapFile: "/images/maps/vermont.svg",
        heroImage: "/images/hero/banner-vt.png",
    },
    {
        slug: "massachusetts",
        name: "Massachusetts",
        abbreviation: "MA",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Massachusetts 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Massachusetts. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for MA residents.",
        dataFile: "/data/forecast-massachusetts.json",
        mapFile: "/images/maps/massachusetts.svg",
        heroImage: "/images/hero/banner-ma.png",
    },
    {
        slug: "connecticut",
        name: "Connecticut",
        abbreviation: "CT",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Connecticut 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Connecticut. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for CT residents.",
        dataFile: "/data/forecast-connecticut.json",
        mapFile: "/images/maps/connecticut.svg",
        heroImage: "/images/hero/banner-ct.png",
    },
    {
        slug: "rhode-island",
        name: "Rhode Island",
        abbreviation: "RI",
        riskRegion: "northeast",
        metaTitle: "Tick Forecast Rhode Island 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Rhode Island. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for RI residents.",
        dataFile: "/data/forecast-rhode-island.json",
        mapFile: "/images/maps/rhode-island.svg",
        heroImage: "/images/hero/banner-ri.png",
    },
    {
        slug: "new-york",
        name: "New York",
        abbreviation: "NY",
        riskRegion: "mid-atlantic",
        metaTitle: "Tick Forecast New York 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in New York. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for NY residents.",
        dataFile: "/data/forecast-new-york.json",
        mapFile: "/images/maps/new-york.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "new-jersey",
        name: "New Jersey",
        abbreviation: "NJ",
        riskRegion: "mid-atlantic",
        metaTitle: "Tick Forecast New Jersey 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in New Jersey. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for NJ residents.",
        dataFile: "/data/forecast-new-jersey.json",
        mapFile: "/images/maps/new-jersey.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "pennsylvania",
        name: "Pennsylvania",
        abbreviation: "PA",
        riskRegion: "mid-atlantic",
        metaTitle: "Tick Forecast Pennsylvania 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Pennsylvania. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for PA residents.",
        dataFile: "/data/forecast-pennsylvania.json",
        mapFile: "/images/maps/pennsylvania.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "delaware",
        name: "Delaware",
        abbreviation: "DE",
        riskRegion: "mid-atlantic",
        metaTitle: "Tick Forecast Delaware 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Delaware. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for DE residents.",
        dataFile: "/data/forecast-delaware.json",
        mapFile: "/images/maps/delaware.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "maryland",
        name: "Maryland",
        abbreviation: "MD",
        riskRegion: "mid-atlantic",
        metaTitle: "Tick Forecast Maryland 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Maryland. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for MD residents.",
        dataFile: "/data/forecast-maryland.json",
        mapFile: "/images/maps/maryland.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "virginia",
        name: "Virginia",
        abbreviation: "VA",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast Virginia 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Virginia. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for VA residents.",
        dataFile: "/data/forecast-virginia.json",
        mapFile: "/images/maps/virginia.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "west-virginia",
        name: "West Virginia",
        abbreviation: "WV",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast West Virginia 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in West Virginia. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for WV residents.",
        dataFile: "/data/forecast-west-virginia.json",
        mapFile: "/images/maps/west-virginia.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "north-carolina",
        name: "North Carolina",
        abbreviation: "NC",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast North Carolina 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in North Carolina. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for NC residents.",
        dataFile: "/data/forecast-north-carolina.json",
        mapFile: "/images/maps/north-carolina.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "south-carolina",
        name: "South Carolina",
        abbreviation: "SC",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast South Carolina 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in South Carolina. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for SC residents.",
        dataFile: "/data/forecast-south-carolina.json",
        mapFile: "/images/maps/south-carolina.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "georgia",
        name: "Georgia",
        abbreviation: "GA",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast Georgia 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Georgia. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for GA residents.",
        dataFile: "/data/forecast-georgia.json",
        mapFile: "/images/maps/georgia.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "florida",
        name: "Florida",
        abbreviation: "FL",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast Florida 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Florida. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for FL residents.",
        dataFile: "/data/forecast-florida.json",
        mapFile: "/images/maps/florida.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "alabama",
        name: "Alabama",
        abbreviation: "AL",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast Alabama 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Alabama. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for AL residents.",
        dataFile: "/data/forecast-alabama.json",
        mapFile: "/images/maps/alabama.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "tennessee",
        name: "Tennessee",
        abbreviation: "TN",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast Tennessee 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Tennessee. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for TN residents.",
        dataFile: "/data/forecast-tennessee.json",
        mapFile: "/images/maps/tennessee.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "kentucky",
        name: "Kentucky",
        abbreviation: "KY",
        riskRegion: "southeast",
        metaTitle: "Tick Forecast Kentucky 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Kentucky. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for KY residents.",
        dataFile: "/data/forecast-kentucky.json",
        mapFile: "/images/maps/kentucky.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "ohio",
        name: "Ohio",
        abbreviation: "OH",
        riskRegion: "midwest",
        metaTitle: "Tick Forecast Ohio 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Ohio. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for OH residents.",
        dataFile: "/data/forecast-ohio.json",
        mapFile: "/images/maps/ohio.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "indiana",
        name: "Indiana",
        abbreviation: "IN",
        riskRegion: "midwest",
        metaTitle: "Tick Forecast Indiana 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Indiana. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for IN residents.",
        dataFile: "/data/forecast-indiana.json",
        mapFile: "/images/maps/indiana.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "illinois",
        name: "Illinois",
        abbreviation: "IL",
        riskRegion: "midwest",
        metaTitle: "Tick Forecast Illinois 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Illinois. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for IL residents.",
        dataFile: "/data/forecast-illinois.json",
        mapFile: "/images/maps/illinois.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "michigan",
        name: "Michigan",
        abbreviation: "MI",
        riskRegion: "midwest",
        metaTitle: "Tick Forecast Michigan 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Michigan. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for MI residents.",
        dataFile: "/data/forecast-michigan.json",
        mapFile: "/images/maps/michigan.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: "wisconsin",
        name: "Wisconsin",
        abbreviation: "WI",
        riskRegion: "midwest",
        metaTitle: "Tick Forecast Wisconsin 2026 | Tick Activity & Lyme Risk",
        metaDescription: "See current tick activity in Wisconsin. Get the 2026 tick forecast, Lyme disease risk maps, and prevention tips for WI residents.",
        dataFile: "/data/forecast-wisconsin.json",
        mapFile: "/images/maps/wisconsin.svg",
        heroImage: "/images/states/generic-hero.png",
    },
    {
        slug: 'minnesota',
        name: 'Minnesota',
        abbreviation: 'MN',
        riskRegion: 'Upper Midwest',
        metaTitle: 'Minnesota Tick Forecast & Lyme Disease Risk',
        metaDescription: 'Current tick activity forecast for Minnesota. High risk in North Woods and Cabin Country. Check local tick encounter levels.',
        dataFile: 'mn_data.json',
        mapFile: 'mn_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'mississippi',
        name: 'Mississippi',
        abbreviation: 'MS',
        riskRegion: 'South',
        metaTitle: 'Mississippi Tick Forecast & Seasonality',
        metaDescription: 'Tick activity forecast for Mississippi. Year-round risk for Lone Star and Gulf Coast ticks. Protect yourself from tick-borne diseases.',
        dataFile: 'ms_data.json',
        mapFile: 'ms_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'louisiana',
        name: 'Louisiana',
        abbreviation: 'LA',
        riskRegion: 'South',
        metaTitle: 'Louisiana Tick Forecast & Risk Map',
        metaDescription: 'Current tick forecast for Louisiana. High activity in bayous and pine forests. Learn about local tick species and risks.',
        dataFile: 'la_data.json',
        mapFile: 'la_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'arkansas',
        name: 'Arkansas',
        abbreviation: 'AR',
        riskRegion: 'South',
        metaTitle: 'Arkansas Tick Forecast & Ozark Tick Risk',
        metaDescription: 'Arkansas tick season update. High risk in the Ozarks and Ouachitas. Monitor Lone Star tick activity and disease risks.',
        dataFile: 'ar_data.json',
        mapFile: 'ar_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'texas',
        name: 'Texas',
        abbreviation: 'TX',
        riskRegion: 'Southwest',
        metaTitle: 'Texas Tick Forecast & Seasonality',
        metaDescription: 'Tick forecast for Texas. From East Texas forests to Hill Country, know your tick risk. Year-round activity in many areas.',
        dataFile: 'tx_data.json',
        mapFile: 'tx_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'oklahoma',
        name: 'Oklahoma',
        abbreviation: 'OK',
        riskRegion: 'Southwest',
        metaTitle: 'Oklahoma Tick Forecast & Risk Levels',
        metaDescription: 'Current tick activity in Oklahoma. High risk in Green Country and eastern woodlands. Stay safe from tick-borne illnesses.',
        dataFile: 'ok_data.json',
        mapFile: 'ok_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'missouri',
        name: 'Missouri',
        abbreviation: 'MO',
        riskRegion: 'Midwest',
        metaTitle: 'Missouri Tick Forecast & Lyme Risk',
        metaDescription: 'Missouri tick forecast. High biodiversity of ticks in the Ozarks and Mark Twain National Forest. Check current risk levels.',
        dataFile: 'mo_data.json',
        mapFile: 'mo_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'iowa',
        name: 'Iowa',
        abbreviation: 'IA',
        riskRegion: 'Midwest',
        metaTitle: 'Iowa Tick Forecast & Seasonality',
        metaDescription: 'Tick activity forecast for Iowa. Rising Lyme disease risk in eastern counties. Monitor deer tick and dog tick activity.',
        dataFile: 'ia_data.json',
        mapFile: 'ia_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'kansas',
        name: 'Kansas',
        abbreviation: 'KS',
        riskRegion: 'Plains',
        metaTitle: 'Kansas Tick Forecast & Risk Map',
        metaDescription: 'Kansas tick forecast. Seasonal risk for American Dog ticks and Lone Star ticks. Stay informed about tick activity.',
        dataFile: 'ks_data.json',
        mapFile: 'ks_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'nebraska',
        name: 'Nebraska',
        abbreviation: 'NE',
        riskRegion: 'Plains',
        metaTitle: 'Nebraska Tick Forecast & Activity',
        metaDescription: 'Current tick risk in Nebraska. Focus on river valleys and wooded areas. American Dog tick and Lone Star tick updates.',
        dataFile: 'ne_data.json',
        mapFile: 'ne_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'south-dakota',
        name: 'South Dakota',
        abbreviation: 'SD',
        riskRegion: 'Plains',
        metaTitle: 'South Dakota Tick Forecast & Black Hills Risk',
        metaDescription: 'South Dakota tick forecast. High risk in the Black Hills and river corridors. Monitor wood tick activity.',
        dataFile: 'sd_data.json',
        mapFile: 'sd_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'north-dakota',
        name: 'North Dakota',
        abbreviation: 'ND',
        riskRegion: 'Plains',
        metaTitle: 'North Dakota Tick Forecast & Wood Tick Risk',
        metaDescription: 'North Dakota tick forecast. Seasonal risk for American Dog ticks and Wood ticks. Stay safe in the Badlands and river valleys.',
        dataFile: 'nd_data.json',
        mapFile: 'nd_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'montana',
        name: 'Montana',
        abbreviation: 'MT',
        riskRegion: 'Mountain West',
        metaTitle: 'Montana Tick Forecast & Rocky Mountain Wood Tick',
        metaDescription: 'Montana tick forecast. High risk in Western Montana forests and river bottoms. Learn about Rocky Mountain Wood Tick activity.',
        dataFile: 'mt_data.json',
        mapFile: 'mt_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'wyoming',
        name: 'Wyoming',
        abbreviation: 'WY',
        riskRegion: 'Mountain West',
        metaTitle: 'Wyoming Tick Forecast & Colorado Tick Fever',
        metaDescription: 'Wyoming tick forecast. Seasonal risk in Yellowstone, Tetons, and lower elevations. Watch for Rocky Mountain Wood Ticks.',
        dataFile: 'wy_data.json',
        mapFile: 'wy_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'colorado',
        name: 'Colorado',
        abbreviation: 'CO',
        riskRegion: 'Mountain West',
        metaTitle: 'Colorado Tick Forecast & Tick Fever Risk',
        metaDescription: 'Colorado tick forecast. High risk for Colorado Tick Fever in the mountains. Check tick activity in the Front Range and Rockies.',
        dataFile: 'co_data.json',
        mapFile: 'co_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'new-mexico',
        name: 'New Mexico',
        abbreviation: 'NM',
        riskRegion: 'Southwest',
        metaTitle: 'New Mexico Tick Forecast & Plague Risk',
        metaDescription: 'New Mexico tick forecast. Monitor risks for Plague and Tularemia in high desert and mountain areas. Stay safe outdoors.',
        dataFile: 'nm_data.json',
        mapFile: 'nm_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'washington',
        name: 'Washington',
        abbreviation: 'WA',
        riskRegion: 'West Coast',
        metaTitle: 'Washington Tick Forecast & Lyme Risk',
        metaDescription: 'Washington tick forecast. High risk in Western Washington for Lyme disease. Monitor tick activity in forests and coastal areas.',
        dataFile: 'wa_data.json',
        mapFile: 'wa_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'oregon',
        name: 'Oregon',
        abbreviation: 'OR',
        riskRegion: 'West Coast',
        metaTitle: 'Oregon Tick Forecast & Western Blacklegged Tick',
        metaDescription: 'Oregon tick forecast. Lyme disease risk in Western Oregon. Stay safe in the Willamette Valley and coastal forests.',
        dataFile: 'or_data.json',
        mapFile: 'or_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'california',
        name: 'California',
        abbreviation: 'CA',
        riskRegion: 'West Coast',
        metaTitle: 'California Tick Forecast & Lyme Disease Risk',
        metaDescription: 'California tick forecast. Year-round tick activity in coastal counties. Monitor Western Blacklegged Tick risks in Bay Area and NorCal.',
        dataFile: 'ca_data.json',
        mapFile: 'ca_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'idaho',
        name: 'Idaho',
        abbreviation: 'ID',
        riskRegion: 'Mountain West',
        metaTitle: 'Idaho Tick Forecast & Rocky Mountain Wood Tick',
        metaDescription: 'Idaho tick forecast. High risk in spring for Rocky Mountain Wood Ticks. Stay safe in national forests and river valleys.',
        dataFile: 'id_data.json',
        mapFile: 'id_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'utah',
        name: 'Utah',
        abbreviation: 'UT',
        riskRegion: 'Mountain West',
        metaTitle: 'Utah Tick Forecast & Tick Fever Risk',
        metaDescription: 'Utah tick forecast. Seasonal risk in mountains and canyons. Watch for Colorado Tick Fever and Tularemia.',
        dataFile: 'ut_data.json',
        mapFile: 'ut_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'nevada',
        name: 'Nevada',
        abbreviation: 'NV',
        riskRegion: 'Southwest',
        metaTitle: 'Nevada Tick Forecast & Rocky Mountain Spotted Fever',
        metaDescription: 'Nevada tick forecast. Low overall risk but hotspots exist in mountains and near water. Watch for soft ticks in cabins.',
        dataFile: 'nv_data.json',
        mapFile: 'nv_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'arizona',
        name: 'Arizona',
        abbreviation: 'AZ',
        riskRegion: 'Southwest',
        metaTitle: 'Arizona Tick Forecast & Brown Dog Tick Risk',
        metaDescription: 'Arizona tick forecast. High risk of RMSF from Brown Dog Ticks. Stay safe in high country forests and rural communities.',
        dataFile: 'az_data.json',
        mapFile: 'az_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'alaska',
        name: 'Alaska',
        abbreviation: 'AK',
        riskRegion: 'Non-Contiguous',
        metaTitle: 'Alaska Tick Forecast & Haemaphysalis Risk',
        metaDescription: 'Alaska tick forecast. Monitoring the spread of ticks on wildlife and pets. Learn about the "Hare Tick" and invasive species.',
        dataFile: 'ak_data.json',
        mapFile: 'ak_map.json',
        heroImage: '/images/states/generic-hero.png'
    },
    {
        slug: 'hawaii',
        name: 'Hawaii',
        abbreviation: 'HI',
        riskRegion: 'Non-Contiguous',
        metaTitle: 'Hawaii Tick Forecast & Brown Dog Tick',
        metaDescription: 'Hawaii tick forecast. No endemic Lyme disease, but Brown Dog Ticks affect pets. Monitor for invasive species.',
        dataFile: 'hi_data.json',
        mapFile: 'hi_map.json',
        heroImage: '/images/states/generic-hero.png'
    }
];
